---
apiVersion: v1
kind: Namespace
metadata:
  name: gozero
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    matchLabels:
      app: gozero
  template:
    metadata:
      labels:
        app: gozero
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: gozero
        image: rminz/gozero:0.2.5
        imagePullPolicy: Always
        env:
        - name: REDIS_ADDR
          value: redis.gozero.svc.cluster.local
        - name: LOG_LEVEL
          value: debug
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    app: gozero
  ports:
  - port: 8443
    name: proxy
    targetPort: 8443
  - port: 9090
    name: metrics
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gozero
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: gozero
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP