apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: rminz/gozero
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GIT_COMMIT: "{{.GIT_COMMIT}}"
          VERSION: "{{.VERSION}}"
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  local:
    push: true