---
apiVersion: v1
kind: Namespace
metadata:
  name: gozero
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    matchLabels:
      app: gozero
  template:
    metadata:
      labels:
        app: gozero
    spec:
      containers:
      - name: gozero
        image: rminz/gozero:0.0.10
        env:
        - name: REDIS_ADDR
          value: redis.redis.svc.cluster.local
        - name: LOG_LEVEL
          value: debug
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    app: gozero
  ports:
  - port: 8443
    name: proxy
    targetPort: 8443
  - port: 9090
    name: metrics
    targetPort: 9090
