---
apiVersion: v1
kind: Namespace
metadata:
  name: gozero
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    matchLabels:
      app: gozero
  template:
    metadata:
      labels:
        app: gozero
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: gozero
        image: rminz/gozero:0.2.4
        env:
        - name: REDIS_ADDR
          value: redis.gozero.svc.cluster.local
        - name: LOG_LEVEL
          value: debug
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gozero
  namespace: gozero
spec:
  selector:
    app: gozero
  ports:
  - port: 8443
    name: proxy
    targetPort: 8443
  - port: 9090
    name: metrics
    targetPort: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gozero
  namespace: gozero
spec:
  host: gozero.gozero.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        h2UpgradePolicy: UPGRADE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gozero
  namespace: gozero
spec:
  hosts:
  - gozero.gozero.svc.cluster.local
  exportTo:
  - "*"
  http:
  - route:
    - destination:
        host: gozero.gozero.svc.cluster.local
        port:
          number: 8443
