apiVersion: v1
kind: Namespace
metadata:
  name: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "gozero.labels" . | nindent 4 }}
    {{- if .Values.istioInjection }}
    istio-injection: enabled
    {{- end }}
