apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-a
  namespace: app-a
spec:
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 2
  scaleTargetRef:
    name: app
    apiVersion: apps/v1
    kind: Deployment
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "1"
      format: "json"
      activationTargetValue: "1"
      url: "http://gozero.gozero.svc.cluster.local:9090/metrics/app-app-a-svc-cluster-local"
      valueLocation: "value"
